services:
  - type: web
    name: meta
    runtime: python
    pythonVersion: 3.11.9
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
